# the controller_manager will start the controllers and parameters
# and the robot_state_publisher will publish the state of the robot
# to the tf2 system
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    
    # give a name to conrollers and give it a type
    # and give it parameters

    # this is the controller that will publish the state of the robot
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    # this is the controller that will control the robot
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["base_wheel2_joint"]
    right_wheel_names: ["base_wheel1_joint"]

    wheel_separation: 0.34 # meters
    wheel_radius: 0.1 # meters

    publish_rate: 50.0 # Hz
    enable_odom_tf: true
    
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # velocity limits
    linear.x.max_velocity: 1.5 # m/s
    linear.x.min_velocity: -1.5 # m/s
    angular.z.max_velocity: 1.0 # rad/s
    angular.z.min_velocity: -1.0 # rad/s
